version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: laravel_app
    volumes:
      - ./src:/var/www/html:cached
    networks:
      - laravel-network
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: 8G

  webserver:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network
    depends_on:
      - app
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    env_file:
      - ./src/.env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - laravel-network
    command: --default-authentication-plugin=mysql_native_password --max_connections=300
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
   
volumes:
  mysql_data:
  mssql_data:

networks:
  laravel-network:
    driver: bridge