version: '3.8'

services:
  app:
    build:
      context: ./php
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - laravel
    depends_on:
      - mysql
    command: bash -c "composer install && npm install && php-fpm"

  nginx:
    image: nginx:stable-alpine
    container_name: laravel-nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
