version: '3.8'

services:
  php:
    image: php:8.1.29-apache
    container_name: meu_php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - C:/Users/alber/OneDrive/Documents/Controle_Estoque:/var/www/html
    links:
      - db

  db:
    image: mysql:latest
    container_name: meu-mysql-php
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  composer:
    image: composer:latest
    container_name: meu_composer
    volumes:
      - C:/Users/alber/OneDrive/Documents/Controle_Estoque:/var/www/html
    working_dir: /var/www/html
    command: ["composer", "install"]

  node:
    image: node:latest
    container_name: meu_node
    volumes:
      - C:/Users/alber/OneDrive/Documents/Controle_Estoque:/var/www/html
    working_dir: /var/www/html
    command: ["npm", "install"]
