version: '3.8'

services:
  app:
    build:
      context: ./php
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - laravel
    depends_on:
      - mysql

  nginx:
    image: nginx:stable-alpine
    container_name: laravel-nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    ports:
      - "3306:3306"
    env_file:
      - ./src/.env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - laravel
    command: --default-authentication-plugin=mysql_native_password --max_connections=300
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4G

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge
